version: '2'

services:
  kafka:
    image: kafka:cv-poc
    hostname: kafka
    container_name: kafka
    domainname: computer-vision
    networks: 
      - computer-vision
    volumes:
      - ./dataset/:/opt/dataset
  zookeeper:
    image: zookeeper:cv-poc
    hostname: zookeeper
    container_name: zookeeper
    domainname: computer-vision
    networks: 
      - computer-vision
  landoop:
    image: landoop:cv-poc
    hostname: landoop
    container_name: landoop
    domainname: computer-vision
    networks:
      - computer-vision

networks:
  computer-vision:
    driver: bridge
